name: SonarQubeProyectoVue

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        # Hash SHA verificado para v5.0.0
        uses: SonarSource/sonarqube-scan-action@53c3e3207621be945b08ec8bf0fc7b6de3732ee1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
